/**
 * GameAssetRegistry ABI
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT IS AN ABI?
 * ABI = Application Binary Interface.
 *
 * Smart contract bytecode is just raw hex on-chain. To call a function like
 * getAsset(1), your code needs to know:
 *   - The function's 4-byte selector (keccak256 hash of its signature)
 *   - How to ABI-encode the arguments (uint256, address, etc.)
 *   - How to ABI-decode the return value
 *
 * The ABI JSON is generated by the Solidity compiler and captures all of this.
 * Ethers.js reads it and handles encoding/decoding automatically.
 *
 * We keep a manual copy here so the API works without running the full
 * Hardhat compile step in production. Only includes the functions our API calls.
 * ─────────────────────────────────────────────────────────────────────────────
 */
export const GAME_ASSET_REGISTRY_ABI = [
  // ── READ FUNCTIONS ──────────────────────────────────────────────────────
  {
    name: "getAsset",
    type: "function",
    stateMutability: "view", // view = read-only, no gas cost when called via eth_call
    inputs: [
      { name: "assetId", type: "uint256" }
    ],
    outputs: [
      { name: "owner",        type: "address" },
      { name: "name",         type: "string"  },
      { name: "assetType",    type: "string"  },
      { name: "rarity",       type: "uint8"   }, // enum is uint8 in ABI
      { name: "metadataURI",  type: "string"  },
      { name: "registeredAt", type: "uint256" },
    ],
  },
  {
    name: "assetExistsCheck",
    type: "function",
    stateMutability: "view",
    inputs:  [{ name: "assetId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs:  [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getRegistryStats",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [
      { name: "total",            type: "uint256" },
      { name: "registrarAddress", type: "address" },
    ],
  },
  {
    name: "totalAssets",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{ name: "", type: "uint256" }],
  },

  // ── WRITE FUNCTIONS ─────────────────────────────────────────────────────
  {
    name: "registerAsset",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assetId",     type: "uint256" },
      { name: "owner",       type: "address" },
      { name: "name",        type: "string"  },
      { name: "assetType",   type: "string"  },
      { name: "rarity",      type: "uint8"   },
      { name: "metadataURI", type: "string"  },
    ],
    outputs: [],
  },
  {
    name: "transferAsset",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assetId", type: "uint256" },
      { name: "to",      type: "address" },
    ],
    outputs: [],
  },

  // ── EVENTS ──────────────────────────────────────────────────────────────
  {
    name: "AssetRegistered",
    type: "event",
    inputs: [
      { name: "assetId",   type: "uint256", indexed: true  },
      { name: "owner",     type: "address", indexed: true  },
      { name: "name",      type: "string",  indexed: false },
      { name: "rarity",    type: "uint8",   indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
  },
  {
    name: "AssetTransferred",
    type: "event",
    inputs: [
      { name: "assetId",   type: "uint256", indexed: true  },
      { name: "from",      type: "address", indexed: true  },
      { name: "to",        type: "address", indexed: true  },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
  },

  // ── ERRORS ──────────────────────────────────────────────────────────────
  { name: "NotRegistrar",   type: "error", inputs: [] },
  { name: "AssetNotFound",  type: "error", inputs: [{ name: "assetId", type: "uint256" }] },
  { name: "NotAssetOwner",  type: "error", inputs: [
    { name: "assetId", type: "uint256" },
    { name: "caller",  type: "address" },
  ]},
] as const;

// Human-readable rarity names — maps the uint8 from chain to display string
export const RARITY_LABELS: Record<number, string> = {
  0: "Common",
  1: "Uncommon",
  2: "Rare",
  3: "Epic",
  4: "Legendary",
};
