apiVersion: v1
kind: ConfigMap
metadata:
  name: staging-config
  labels:
    environment: staging
data:
  mongodb_uri: "mongodb://admin:stagingpassword@mongodb:27017/web3games?authSource=admin"
  hardhat_rpc_url: "http://hardhat:8545"
  next_public_rpc_url: "https://your-staging-domain.com:8545"
