apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: web3games-staging
  namespace: web3games-staging

namespace: web3games-staging

commonLabels:
  environment: staging
  app: web3games

resources:
  - configmap.yaml
  - backend-blue-green.yaml
  - frontend-blue-green.yaml
  - hardhat.yaml

commonAnnotations:
  deployment-type: blue-green
  gitops: "true"
  canary-duration: "600"
